swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Branning Geocoder"
  termsOfService: "https://branning.github.io/geocoder/terms"
  contact:
    email: "branning+geocoder@gmail.com"
  license:
    name: "MIT"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1"
basePath: "/v2"
tags:
- name: "geocoder"
  externalDocs:
    description: "About Geocoder"
    url: "https://branning.github.io/geocoder"
schemes:
- "https"
#- "http"
paths:
  /latlong:
    get:
      tags:
      - "geocoder"
      summary: "Address to latitude and longitude"
      description: "A free text address is provided as a query parameter, and latitude and longtitude coordinates are retrieved from the first available geocoding service"
      operationId: "getCoordinates"
      produces:
      - "application/json"
      parameters:
      - name: "address"
        in: "query"
        description: "free text address"
        required: true
        type: "string"
        items:
          type: "string"
          default: "1600 Amphitheatre Parkway, Mountain View, CA"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Coordinates"
        400:
          description: "Invalid address"
      security:
      - geocoder_auth:
        - "read:geocoder"
  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid username/password supplied"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
securityDefinitions:
  geocoder_auth:
    type: "oauth2"
    authorizationUrl: "http://127.0.0.1/oauth/dialog"
    flow: "implicit"
    scopes:
      read:geocoder: "retrieve coordinates for an anddress"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Coordinates:
    type: "object"
    properties:
      latitude:
        type: "number"
        format: "float"
      longitude:
        type: "number"
        format: "float"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"